### ISSUE TITLE
Server side rendered open modal

### ISSUE THREAD

**Issue by ruszki** [reactstrap/reactstrap#1071]
### Issue description

- components: Modal
- reactstrap version 5.0.0, but the problematic code still exists in latest version
- import method: es with Webpack
- react version 16.2.0
- bootstrap version 4.0.0

### What is happening?

When an open modal is server side rendered, then it is failing with "document is not defined". The exception is thrown in Modal's init method.

### What should be happening?

Render as it should. Probably move checking of isOpen, and calling of init to componentDidMount from constructor.

### Steps to reproduce issue

1. Create a modal with isOpen true.
2. Try render it with React's renderToString.

### Error message in console

```
ReferenceError: document is not defined
    at Modal.init (...)
    at new Modal (...)
    at resolve (...)
    at ReactDOMServerRenderer.render (...)
    at ReactDOMServerRenderer.read (...)
    at renderToString (...)
```

### Code

```
import {renderToString} from "react-dom/server";

renderToString(
    <Modal isOpen>
        <ModalBody>Lorem ipsum</ModalBody>
    </Modal>);
```

**Comment by jordan-jarolim** [comment]
Same issue here! It would be great to have a possibility of opened modal on load/init.

**Comment by virgofx** [comment]
Just need feedback ... everyone okay with it opening immediately via `componentDidMount` ???

Only downside is that the true HTML sent down from server wouldn't match the opened HTML (not really a downside just if someone cared 100% about showing the modal content being open/in correct DOM location in source -- who needs that/cares?)

It would not be noticeable and look better as when loading the page it would slide the modal down instead of already be open (no transition).

**Comment by virgofx** [comment]
@TheSharpieOne That library is one of many techniques as mentioned in my above comment. Essentially, those libraries are JavaScript backend specific which wouldn't work for our case which is a library (we shouldn't provide/expect a specific backend).

Backends = NodeJs via Express, PHP via V8JS, etc.

We would have to mimic that functionality and provide some escape hatches to render the Modal portals separately  (which we could do -- my thought is that most people that are running SSR are less likely simply executing static code and more likely hydrating on the client and thus , the simplest solution would be to perform in componentDidMount()).

Otherwise, we would have to store all the portals specifically rendered via Reactstrap and then provide a separate hook to retrieve those ... such that the backend provider could inject as necessary.

**Comment by TheSharpieOne** [comment]
Yeah, that makes sense. Lets go with the lighter hydrating method

**Comment by virgofx** [comment]
Sounds good. Will reference this issue with PR (hopefully this weekend)

**Comment by eliaszs** [comment]
@virgofx Is there any update on this?

**Comment by virgofx** [comment]
Sorry not yet ... been super busy should only be a quick fix to migrate the opening portion to trigger client side ... give me another week should have it done unless you want to submit a PR ... always welcome as well.

**Comment by seeden** [comment]
any update?

**Comment by lamhieu-vk** [comment]
resolved at https://github.com/reactstrap/reactstrap/pull/1495

**Comment by boutdemousse** [comment]
This problem is still here (reactstrap 8.0.0) but the fix is quite simple : 
```
<Modal isOpen={typeof(document) !== 'undefined' ? true : false}>
</Modal>
```

And the error with `isOpen` set to true is : 
```
ReferenceError: document is not defined
    at Modal.init (/home/user/project/node_modules/reactstrap/lib/Modal.js:272:23)
```

**Comment by lamhieu-vk** [comment]
hi @boutdemousse, version 8.0.0 is not included PR's fix this problem. Should you update to version 8.0.1 just released by @TheSharpieOne  at https://github.com/reactstrap/reactstrap/commit/ce2a9a080dd3ac655900865acb98c88124b267ac

**Comment by lamhieu-vk** [comment]
@TheSharpieOne should close this issue?

**Comment by Vadorequest** [comment]
Using Next.js, this issue crashes the whole app when loading a Tooltip that has `isOpen={true}` on the server.
