### ISSUE TITLE
Tooltip no longer working with ref's in v8

### ISSUE THREAD

**Issue by sarah-clements** [reactstrap/reactstrap#1472]
- components: `UncontrolledTooltip`, `Tooltip`
- reactstrap version `#8.0.0`
- import method `es` 
- react version `#16.8.6`
- bootstrap version `#4.3.1`

### What is happening?

The tooltip no longer show on mouse over whereas it worked fine in v7.1.0. I also tried changing this to a stateful `Tooltip`, which also did not work.

### Error message in console
No error shown

### Code
```
export default class SimpleTooltip extends React.Component {
  constructor(props) {
    super(props);
    this.tooltipRef = React.createRef();
  }

  render() {
    const {
      text,
      tooltipText,
      placement,
      textClass,
      tooltipClass,
    } = this.props;

    return (
      <div>
        <span ref={this.tooltipRef} className={textClass}>
          {text}
        </span>
        <UncontrolledTooltip
          placement={placement}
          target={this.tooltipRef}
          className="tooltip"
          innerClassName={tooltipClass}
        >
          {tooltipText}
        </UncontrolledTooltip>
      </div>
    );
  }
}
```

**Comment by OksanaFirtych** [comment]
I have the same issue. It stopped work with reactstrap version upgrade

**Comment by sarah-clements** [comment]
Hi @TheSharpieOne, will this bug be triaged or prioritized any time soon? It's blocking my team from upgrading.

**Comment by TheSharpieOne** [comment]
Hi @sarah-clements. The code provided appears to work in the latest version (8.2.0). Check out this demo: https://stackblitz.com/edit/reactstrap-v8-fpj8sq?file=Example.js

The only thing I can think of is that you might be running into #1457, but if that was the case, you should see some errors in the console.

**Comment by sarah-clements** [comment]
@TheSharpieOne This still doesn't work as expected. If there is more elements on the page than just one line of text, the tooltip placement is off and is shoved further down from where it should be (in your example, tooltip should be aligned to the "hover" text). Any ideas?

![Screen Shot 2020-01-14 at 2 27 06 PM](https://user-images.githubusercontent.com/19615783/72388151-09003380-36da-11ea-88d7-1dd16b4aa20b.png)

**Comment by TheSharpieOne** [comment]
@sarah-clements I think that particular part may be related to #1736
While refs should be working, when the event is triggered in the ref'ed element, its target is the inner most / direct element. #1746 should fix that, but it hasn't been released. I'll try to get it out tomorrow.

**Comment by sarah-clements** [comment]
I tried that version but I'm still seeing this issue (the tooltip should be aligned with "testing" text). So on pages with complex tables/deeply nested elements using the Tooltip, I can't see anything render.

With no other elements, just a Tooltip nested in a div and Container I see this:
![Screen Shot 2020-01-15 at 11 10 43 AM](https://user-images.githubusercontent.com/19615783/72463405-022ffa00-3788-11ea-84d6-aaf9a5a46bdc.png)

As the view is normally, I see this: 
![Screen Shot 2020-01-15 at 11 11 19 AM](https://user-images.githubusercontent.com/19615783/72463421-09ef9e80-3788-11ea-8d20-76e3c28b7909.png)

**Comment by TheSharpieOne** [comment]
Ok, so I looked more into the example provided in the original post. There is a `className` being added to the `UncontrolledTooltip` within the `SimpleTooltip` component. That className is `tooltip`, which is a class defined in bootstrap. `UncontrolledTooltip` (and `Tooltip`) from reactstrap is already adding that bootstrap class. This causes some nested `.tooltip` where the `position: absolute` nesting is messing up the positioning.
Remove that extra className (or change it's name if you have custom styles) and it should work.
Check this out: https://stackblitz.com/edit/reactstrap-v8-xv9nla?file=SimpleTooltip.js

![tooltip-classname-problem](https://user-images.githubusercontent.com/664714/72464563-8479e780-37a3-11ea-93d9-7d4e147bd3ca.gif)

**Comment by sarah-clements** [comment]
Oh! I tried changing everything *but* that! Thanks @TheSharpieOne!

**Comment by sarah-clements** [comment]
This seems to work fine even with v8.2.0 so closing the issue.
