### ISSUE TITLE
Grow Spinner not displaying on iOS Safari

### ISSUE THREAD

**Issue by kimfucious** [reactstrap/reactstrap#1826]
- components: `Spinner`
- reactstrap version `8.4.1`
- import method `import { Spinner } from "reactstrap";`
- react version `16.13.1`
- bootstrap version `4.4.1`

### What is happening?

The following code block shows a "grow" spinner in Chrome and Firefox on a desktop computer, but it does not show the spinner in Safari on iOS.

```js
<Spinner type="grow" color="danger" size="sm" className="mr-1" />
```
### What should be happening?

The spinner should show in Safari on iOS.

There are no errors.

**Comment by kyletsang** [comment]
This should be fixed in bootstrap 4.5.

**Comment by hisamith** [comment]
> This should be fixed in bootstrap 4.5.

Still doesn't work

[Growing-Spinner](https://reactstrap.github.io/components/spinners/#Growing-Spinner)

**Comment by kyletsang** [comment]
The reactstrap site is still targeting bootstrap 4.4.  You need to include bootstrap 4.5 in your own project.

I tested this against the bootstrap 4.4 and 4.5 documentation on Safari iOS and 4.5 resolves the issue. Try the following links in Safari:

4.4 (not fixed)
https://getbootstrap.com/docs/4.4/components/spinners/#growing-spinner

4.5 (fixed)
https://getbootstrap.com/docs/4.5/components/spinners/#growing-spinner

**Comment by hisamith** [comment]
> The reactstrap site is still targeting bootstrap 4.4. You need to include bootstrap 4.5 in your own project.
> 
> I tested this against the bootstrap 4.4 and 4.5 documentation on Safari iOS and 4.5 resolves the issue. Try the following links in Safari:
> 
> 4.4 (not fixed)
> https://getbootstrap.com/docs/4.4/components/spinners/#growing-spinner
> 
> 4.5 (fixed)
> https://getbootstrap.com/docs/4.5/components/spinners/#growing-spinner
 
Thanks Kyle. It worked

**Comment by Simone-cogno** [comment]
Even in Chrome it was not showing. Fixed with bootstrap 4.5. It will be helpful to update the peer dependencies information in the package.json...
