### ISSUE TITLE
Tree shaking not working in version 9?

### ISSUE THREAD

**Issue by Nabrok** [reactstrap/reactstrap#2427]
- reactstrap version `9.0.1`
- react version `17.0.2`
- bootstrap version `5.1.3`

### What is happening?

Full bundle seems to be included at all times.

Compare: https://bundlephobia.com/package/reactstrap@9.0.1 - Exports Analysis shows everything at the same size
As opposed to: https://bundlephobia.com/package/reactstrap@8.10.1 - Exports Analysis shows different sizes.

### What should be happening?

Unused components should be removed.

**Comment by Sysix** [comment]
Using Webpack v5 and the complete Package is included in my code.
Maybe it will solve the problem when the components are seperated into its own files.  
Webpack is not that clever in tree shaking from a single file ;) 


![grafik](https://user-images.githubusercontent.com/3897725/161087641-ac13b342-d1b8-4b75-9a44-61aae0409c9a.png)

**Comment by shtbik** [comment]
Confirm the problem, tested on the latest [CRA](https://create-react-app.dev/docs/adding-typescript/#installation)

```json
"react": "^18.1.0",
"react-dom": "^18.1.0",
"reactstrap": "^9.1.1"
```

```tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import { Container } from 'reactstrap';

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);
root.render(
  <React.StrictMode>
    <Container>Test</Container>
  </React.StrictMode>,
);
```
![Screen Shot 2022-06-10 at 2 45 19 pm](https://user-images.githubusercontent.com/12717213/172992178-a61dba38-6edc-4288-9bf1-7c9e2f772cb6.png)

![Screen Shot 2022-06-10 at 2 48 27 pm](https://user-images.githubusercontent.com/12717213/172992419-88c75bab-6e69-41ab-9165-4d577b2a242d.png)

**Comment by shtbik** [comment]
Created sandbox for replication
https://github.com/shtbik/reactstrap-tree-shaking-issue

**Comment by shtbik** [comment]
I was trying to build `reactstrap` in different ways but still can't tell the exact reason why it's happening ([microbundle commit](https://github.com/reactstrap/reactstrap/commit/8d5fb537875f7e9b7c710b4cf704897fa4994377)). I noticed that `ReactDOM` doesn't support tree shaking properly but it's peer dependency anyway, and it doesn't explain why the analyzer shows the full list of components. `reactstrap.module.js` behaviour is pretty much the same. Personally, the microbundle does a bit of magic and the major version is still 0, so I ask maintainers (@phpweby) to have a look at what we can do when you have time.

**Comment by adarsh-drishya** [comment]
same issue @shtbik  did you find anything?

**Comment by shtbik** [comment]
@adarsh-drishya I didn't, the issue is still relevant

**Comment by adarsh-drishya** [comment]
can we collaborate to fix it? @shtbik . If yes please mail..adarsh.raj@drishya.ai

**Comment by illiteratewriter** [comment]
@adarsh-drishya this should be fixed with #2667

**Comment by anoop-zfh** [comment]
@adarsh-drishya still facing the same issue

```
"next": "13.1.1",
"react": "18.2.0",
"react-dom": "18.2.0",
"reactstrap": "^9.1.9"
```
![Screenshot 2023-05-10 at 12 58 09 PM](https://github.com/reactstrap/reactstrap/assets/121006561/2b246c30-00e6-432b-a1f5-bdaf974b94c1)

**Comment by anoop0567** [comment]
@adarsh-drishya still facing the same issue

```
"next": "13.1.1",
"react": "18.2.0",
"react-dom": "18.2.0",
"reactstrap": "^9.1.9"
```
![Screenshot 2023-05-10 at 12 58 09 PM](https://github.com/reactstrap/reactstrap/assets/121006561/2b246c30-00e6-432b-a1f5-bdaf974b94c1)
![Screenshot 2023-05-10 at 1 08 24 PM](https://github.com/reactstrap/reactstrap/assets/121006561/ae427158-4dd5-40e8-bc4a-7bfee64d52dc)

**Comment by illiteratewriter** [comment]
[Bundlephobia](https://bundlephobia.com/package/reactstrap@9.1.8) shows it as tree shakable. I'll take a look if that's not the case.
