### ISSUE TITLE
tether.js warning

### ISSUE THREAD

**Issue by ablbol** [reactstrap/reactstrap#438]
I just installed "reactstrap": "^4.5.0", and got the following warning.  What do I need to do to resolve  it?
```
/~/reactstrap-tether/dist/js/tether.js
Critical dependencies:
2:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/reactstrap-tether/dist/js/tether.js 2:479-486
printWarnings @ webpackHotDevClient.js:198
```

**Comment by skene** [comment]
I am getting this same error. Any ideas?

**Comment by davelaflam** [comment]
Looks like it's related to this pull-request, https://github.com/HubSpot/tether/pull/175, so in the interim ReactStrap made a fork, https://www.npmjs.com/package/reactstrap-tether, to resolve the issue, however, the way it's being bundled is why Webpack is complaining about it.

**Comment by greeven** [comment]
So no interim solution for this warning?
(Doing `npm i reactstrap-tether` doesn't solve it for anyone wondering.)

**Comment by pitkane** [comment]
To suppress the warning (for now), add this to your webpack config file:

```
  module: {
    noParse: /node_modules\/reactstrap-tether\/dist\/tether.js/,
```
[Credits to @mverderese ](https://github.com/webpack/webpack/issues/1617#issuecomment-223676403)

**Comment by davelaflam** [comment]
Thanks @pitkane, that worked 👍 , although, I did need to add the `js` directory to the path
```
module: {
    noParse: /node_modules\/reactstrap-tether\/dist\/js\/tether.js/,
```
big thanks for the tip

**Comment by eddywashere** [comment]
This will require a pr that changes the build process and more in https://github.com/reactstrap/tether. I'm more concerned about getting popper.js integrated vs spending time on this warning that is in dev only. I'm happy to accept a pr in that repo that fixes it and I'll bump the release here when it's done.

**Comment by FezVrasta** [comment]
Are there any blockers that prevent you from switch to Popper.js?

**Comment by Skaronator** [comment]
@FezVrasta Boostrap will switch to Popper.js within the next release. So no need to switch/change something on its own. Just wait for the next release - aka Boostrap 4 Beta 1.

**Comment by fabiopaiva** [comment]
This error is breaking my bitbucket pipeline

**Comment by annejohnson** [comment]
I continue to see the warning after adding `noParse` with the right path (where the file definitely lives on my machine).

```
eslint: {
  ...
},
noParse: /node_modules\/reactstrap-tether\/dist\/js\/tether.js/,
plugins: [
  ...
],
```

Does anyone have suggestions?

**Comment by annejohnson** [comment]
My issue is resolved. I'd placed the `noParse` in the wrong place in the webpack config. I had it nested under `module.exports`, when I should have had it nested one level further, in `module.exports.module`.

**Comment by s1012602** [comment]
My `reactstrap` is now ver 4.6.2, and I have added `noParse` to my `webpack.config` like below.

```
 module.exports = {
    module: {
        noParse: /node_modules\/reactstrap-tether\/dist\/js\/tether.js/,
    }
 }
```

But it still appears the warning like above. 
Can anybody help?

**Comment by und0ck3d** [comment]
Is there any PR for this issue already?

I'm currently using brunch and added to my `brunch-config.js` the following:

```
...
conventions: {
  ignored: [
    /^node_modules\/reactstrap-tether\/dist\/js\/tether.js/
  ]
}
...
```

But it doesn't work and outputs the following error:

```
18:23:14 - info: compiled 4 files into 2 files, copied 2 in 1.7 sec
14 Aug 18:23:14 - info: [copycat] copied 10 files
18:23:17 - info: compiling
18:23:17 - error: Processing of node_modules/reactstrap-tether/dist/js/tether.js failed. Error: Could not load module './utils' from '/app/assets/app/node_modules/reactstrap-tether/dist/js'. Make sure the file actually exists.
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn notify-send ENOENT
  at exports._errnoException (util.js:1050:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
  at onErrorNT (internal/child_process.js:367:16)
  at _combinedTickCallback (internal/process/next_tick.js:80:11)
  at process._tickCallback (internal/process/next_tick.js:104:9)
```

Any tip/workaround for Brunch projects? Thanks in advance.

**Comment by supergibbs** [comment]
@TheSharpieOne I think this was mistakenly added to the v5 milestone. The next release uses popperJs instead so this ticket is obsolete and should probably be closed.

**Comment by Skaronator** [comment]
I think @TheSharpieOne added this to the v5 milestone because v5 "fix" this issue by removing tether.js completly.

**Comment by ajbraus** [comment]
I am working with brunch and still am getting this. 

```
error: Processing of node_modules/reactstrap-tether/dist/js/tether.js failed. Error: Could not load module './utils' from '/Users/.../node_modules/reactstrap-tether/dist/js'. Make sure the file actually exists.
```

**Comment by ajbraus** [comment]
This error went away when I installed 5.0.0.beta.2 - but a different error with react-popper emerged.

**Comment by supergibbs** [comment]
Yes, there are some build issues with the latest `react-popper` that affect `reactstrap@5.0.0-beta.2`.

See #870
