### ISSUE TITLE
Modal corrupt after multiple clicks on ModalFooter buttons

### ISSUE THREAD

**Issue by guilleCM** [reactstrap/reactstrap#530]
### Issue description

- version `#4.8.0`
- components: `Modal`

### Steps to reproduce issue
Open a Modal window, try to close the modal by multiple clicks on buttons ('Do Something' or 'Cancel' buttons) placed in ModalFooter component. After this, I can't toggle a new modal because it seems already a TransitionGroup is mounted by React, and the multiple clicks prevents destroy it!!!
It works expected if I just click once in the button, but if I'm faster I can click more than one time and then triggers the bug.
- How can I tell to the 'toogle()' method that if a TransitionGroup is already mounted just return?

**Comment by guilleCM** [comment]
![modalbug](https://user-images.githubusercontent.com/22665560/29073595-7c5e31ce-7c4c-11e7-9d11-043e66b00579.jpg)

**Comment by TheSharpieOne** [comment]
Related to #360 in that simply toggling the `Modal` too quickly corrupts/breaks it.
One of the things that needs to happen will be rethinking animations. `Popovers` and `Tooltips` need animations; `Modal` and `Collapse` have this issue where the state becomes corrupt if it toggles too quickly. There needs to be a consistent interface for animating in/out and starting/stopping animations and callbacks of those events as well as opting in/out of animations and controlling durations.

**Comment by guilleCM** [comment]
Okey, I found the bug. The problem is the Modal after clicking button faster than the modal close effect I also activates the backdrop event, so it turns again the !setState of the modal. To fix it, handle the backdrop event or just pass the prop backdrop='static' to the Modal component =>  `<Modal isOpen={this.state.modal} toggle={this.openModal} className={this.props.className} backdrop='static'>`

**Comment by kopax** [comment]
@guilleCM 
>  handle the backdrop event

Could you provide an example ?

**Comment by TheSharpieOne** [comment]
Fixed in 2cdf225

**Comment by santaclauze** [comment]
Hey, I still see an error with the `Modal`:

version: `"reactstrap": "^5.0.0-alpha.4",`

### Reproduce

Copy, Paste the **nested** `Modal` example from the Doc .
Launch first `Modal`.
Quickly click mutiple times on activation `Button` of the second `Modal`

### Result

![screenshot from 2017-11-21 21-40-08](https://user-images.githubusercontent.com/17665998/33062592-b0a9eb52-cf04-11e7-809a-62524b4f43fd.png)

**Comment by TheSharpieOne** [comment]
That is just a bug in the docs themselves, not the component. A fix is incoming for that.
